- name: Deploy Postfix
  hosts: all
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Deploy Docker Image
      community.docker.docker_container:
        name: POSTFIX
        image: panubo/postfix
        state: started
        restart: true
        env:
          MAILNAME: "{{ postfix_hostname }}"
          MYNETWORKS: "{{ postfix_networks }}"
          TZ: "Europe/Zurich"
          USE_TLS: "no"