---

- name: Deploy Zabbix-Proxy-Container
  hosts: all
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Deploy Docker Image
      community.docker.docker_container:
        name: ZBX-PROXY
        image: zabbix/zabbix-proxy-sqlite3:ol-6.0-latest
        state: started
        restart: true
        env:
          ZBX_HOSTNAME: "{{ zabbix_hostname }}"
          ZBX_SERVER_HOST: "mnt.itcompro.com"