- name: Deploy Postfix
  hosts: all
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Create docs Directory
      file:
        path: /opt/docs
        state: directory
    - name: Deploy Docker Image
      community.docker.docker_container:
        name: MKDOCS
        image: squidfunk/mkdocs-material
        state: started
        restart: true
        ports:
          - "80:8000"
        volumes:
          - /opt/docs:/docs