---
- name: Create Zabbix Docker container
  hosts: all
  tasks:
    community.docker.docker_container:
      name: ZBX-PROXY
      image: zabbix-proxy-sqlite3:ol-6.0-latest
      state: started
      restart: true
      env:
        ZBX_HOSTNAME: TESTZP01
        ZBX_SERVER_HOST: mnt.itcompro.com