---

- name: update all Hosts
  hosts: all
  tasks:
    - name: install updates
      dnf:
        name: "*"
        state: latest
- name: install docker-ce
  hosts: all
  tasks:
    - name: add docker gpp key
      rpm_key: 
        state: present
        key: https://download.docker.com/linux/centos/gpg
    - name: add docker repo
      dnf:
        enablerepo: https://download.docker.com/linux/centos/docker-ce.repo
    - name: install docker-ce, docker-ce-cli and containerd.io
      dnf:
        name: "docker-ce docker-ce-cli containerd.io"
        state: latest
    - name: enable docker service
      systemd:
        name: docker
        enabled: yes
    - name: make rc.local executable
      file: 
        path: /etc/rc.d/rc.local
        mode: '0755'
    - name: run docker service
      systemd:
        name: docker
        state: started